name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

env:
  default_node_version: 18

jobs:
  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ["18", "20", "22"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }} and Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: "package.json"

      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test

  coverage:
    name: Coverage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{env.default_node_version}} and Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.default_node_version}}
          cache: npm
          cache-dependency-path: "package.json"

      - name: Install Dependencies
        run: npm install
      - name: Coverage
        run: npm run test-cov
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{env.default_node_version}} and Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.default_node_version}}
          cache: npm
          cache-dependency-path: "package.json"

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{env.default_node_version}} and Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.default_node_version}}
          cache: npm
          cache-dependency-path: "package.json"

      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
